---
- hosts: localhost
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    - name: password
      prompt: What is your password?
      private: true
  tasks:
    - name: Print a message
      no_log: true
      debug:
        msg: 'Logging in as {{ username }} with password {{ password }}'